### ISSUE TITLE
Leaderboard / benchmark ?

### ISSUE THREAD

**Issue by hbredin** [wq2012/awesome-diarization#3]
It would be nice to also have some kind of *leaderboard* associated to each of the listed datasets.

One (bad) way of doing it would be to use numbers reported in papers. It is bad for several reasons:
- one cannot be sure the exact same evaluation protocol was used
- one cannot be sure the exact same metric was used 

A better way of doing it would be to ask authors to provide their output files and run the evaluation for them (possibly automatically on each pull request) but this does not solve the first problem. We could use `pyannote.metrics` for that.

An even better way would be to ask them to provide runnable pre-trained systems and run them for them but this would need a lot of work to ask from the authors and to setup.

An utopian way would to ask them to provide trainable systems.

Anyway, maybe it is too much to ask and existing challenges like DIHARD and Albayzin are probably enough...

**Comment by wq2012** [comment]
I think it would be a bit too ambitious to maintain a leaderboard for all the work on speaker diarization, since people use different evaluation protocols. I guess it will cause lots of controversies, and receive more blames than wishes.

But, your idea is still a great one. We can have a *Leaderboards* section to list links to different 3rd party leaderboards. Let me set it up. Feel free to add more.

**Comment by hbredin** [comment]
Makes sense. Thanks.

**Comment by BLack-yzf** [comment]
Recently I want to get some related information about the performance of the diarization.But I can not  access the leaderboard now.

**Comment by wq2012** [comment]
It seems the website https://www.stateoftheart.ai/ is down. There's nothing we can do about it, unfortunately.

**Comment by BLack-yzf** [comment]
ohh,that's terrible. Thanks for your reply.
